### ISSUE TITLE
How to setup?

### ISSUE THREAD

**Issue by rafaelrinaldi** [clns/node-commit-msg#3]
I'm trying to setup this tool to help me format commit messages based on Angular standards but it simply doesn't work. I literally copy and pasted the example to my project and I can still bypass all the rules, like nothing is being checked whatsoever. The only warning I get is for empty commit messages.

Help?

**Comment by clns** [comment]
To install it, you simply need to run `npm install commit-msg` in your project root. Then, to make it validate according to the Angular standards, you can configure it by adding the `commitMsg` key in your `package.json` as [in the example](https://github.com/clns/node-commit-msg/blob/master/test/resources/angular/package.json).

**Comment by rafaelrinaldi** [comment]
@clns That's exactly what I'm doing, however the validations are not happening for some reason. I am still able to write bad commit messages and summaries.

I'm using Node.js `4.2.1` and npm `3.7.1`.

**Comment by clns** [comment]
It installs as a [`commit-msg` hook](http://git-scm.com/docs/githooks#_commit_msg), so make sure you have it installed in `.git/hooks/commit-msg`.
