### ISSUE TITLE
Issues when using it installed globally

### ISSUE THREAD

**Issue by jakkarth** [clns/node-commit-msg#7]
I haven't tried it with the "install through packages.json" route because I'm not using node or npm in my project. My apologies if I've overlooked something.

First, I installed it using npm globally:

> npm install commit-msg -g

Then I created myself a text file:

> echo 'Foo bar.' >test.msg

Then I used the tool to validate it:

> commit-msg file test.msg

The output is the following, which looks great:

> Foo bar.
> 
> error (1,8): Commit subject should not end with a period
> 
> Summary:
> - 0/1 valid/total (with warnings: 0)
> - 0% success rate and 0% warnings

But when I check exit status:

> \> echo $?
> 0

Despite having errors, the exit code is 0, so I cannot use it to abort the commit.

I also encountered this additional problem, where a commit message I wrote caused it to crash with a stack trace:

> echo -n 'AGS74' >test.msg
> commit-msg file test.msg

Resulting output:

> fs.js:148
>    throw new ERR_INVALID_CALLBACK();
>    ^
>
> TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
>     at makeCallback (fs.js:148:11)
>     at Object.fs.unlink (fs.js:1016:14)
>     at /usr/local/lib/node_modules/commit-msg/lib/nlp-parser.js:145:32
>     at ChildProcess.exithandler (child_process.js:273:7)
>     at ChildProcess.emit (events.js:182:13)
>     at maybeClose (internal/child_process.js:957:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)

I regret that I am not familiar with node development and cannot diagnose the issue further myself, or provide a pull request. If I can provide any additional information about these issues, please let me know. I would very much like to incorporate this tool into my workflow. Thank you for programming it and releasing it! :)

**Comment by j0d5** [comment]
I also get this one:

> Resulting output:

    fs.js:148
    throw new ERR_INVALID_CALLBACK();
    ^

    TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:148:11)
    at Object.fs.unlink (fs.js:1016:14)
    at /usr/local/lib/node_modules/commit-msg/lib/nlp-parser.js:145:32
    at ChildProcess.exithandler (child_process.js:273:7)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:957:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)

**Comment by clns** [comment]
Fixed by #10
